env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script: pkg install -y go
  build_script: go build -v ./...
  test_script: go test -v ./...
